#!/bin/sh
# sea-shell — recolour the shell accent + kitty from a wallpaper via matugen, or
# reset both to the default sea-cyan when called with --reset.
#
#   matugen-accent.sh [wallpaper]   apply: accent → appearance.json, palette → kitty
#   matugen-accent.sh --reset       revert accent to #63c7dd, clear the kitty overrides
#
# Writes ~/.config/sea-shell/appearance.json (accent, other fields preserved) and
# ~/.config/sea-shell/kitty-matugen.conf (kitty overrides; sea-cyan.conf includes it).
DEFAULT="#63c7dd"
cfg="$HOME/.config/sea-shell/appearance.json"
kitty="$HOME/.config/sea-shell/kitty-matugen.conf"
mkdir -p "$HOME/.config/sea-shell"
reload_kitty() { pkill -USR1 -x kitty 2>/dev/null || true; }

set_accent() {   # $1 = hex, preserving every other appearance.json field
    python3 - "$cfg" "$1" <<'PY'
import json, sys
cfg, col = sys.argv[1], sys.argv[2]
try: d = json.load(open(cfg))
except Exception: d = {"radius": 14, "opacity": 0.82, "height": 42, "font": "monospace"}
d["accent"] = col
json.dump(d, open(cfg, "w"))
PY
}

star="$HOME/.config/starship.toml"
sdef="$HOME/.config/sea-shell/starship-default.toml"

if [ "$1" = "--reset" ]; then
    set_accent "$DEFAULT"
    : > "$kitty"                       # empty → kitty falls back to sea-cyan.conf defaults
    : > "$HOME/.config/sea-shell/kitty-matugen-light.conf"   # clear the light variant too
    [ -f "$sdef" ] && cp "$sdef" "$star" 2>/dev/null   # restore the default sea prompt
    reload_kitty
    notify-send 'sea-shell' 'Colours reset to sea cyan' 2>/dev/null
    exit 0
fi

wp="$1"
[ -z "$wp" ] && wp=$(cat "$HOME/.config/sea-shell/wallpaper" 2>/dev/null)
[ -z "$wp" ] && exit 1
case "$wp" in
    *.mp4|*.webm|*.mkv|*.mov|*.gif)
        f=/tmp/sea-matugen-frame.png
        ffmpeg -y -i "$wp" -vframes 1 "$f" >/dev/null 2>&1 && wp="$f" ;;
esac

json=$(matugen --json hex --prefer saturation image "$wp" 2>/dev/null)
[ -z "$json" ] && exit 1
# stash the JSON in a temp file — stdin is taken by the heredoc program below
jf=$(mktemp) || exit 1
printf '%s' "$json" > "$jf"

# accent = Material `primary`; kitty ANSI palette = the base16 scheme (dark variant).
# prints "<accent> <frost>" on stdout so the shell can also recolour starship.
pal=$(python3 - "$cfg" "$kitty" "$DEFAULT" "$jf" <<'PY'
import json, sys
cfg, kitty, default, jf = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
data = json.load(open(jf))
def pick(node):
    if not node: return None
    return (node.get('dark') or node.get('default') or node.get('light') or {}).get('color')
def lighten(hx, amt=0.30):
    h = hx.lstrip('#'); r, g, b_ = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
    return '#%02x%02x%02x' % (int(r+(255-r)*amt), int(g+(255-g)*amt), int(b_+(255-b_)*amt))
colors = data.get('colors', {}); b = data.get('base16', {})
def bb(k, fb): return pick(b.get(k)) or fb
accent = pick(colors.get('primary')) or default

try: d = json.load(open(cfg))
except Exception: d = {"radius": 14, "opacity": 0.82, "height": 42, "font": "monospace"}
d["accent"] = accent
json.dump(d, open(cfg, "w"))

bg = bb('base00', '#0d1420'); fg = bb('base05', '#e2e9f4')
m = [
 ('foreground', fg), ('background', bg),
 ('selection_foreground', bg), ('selection_background', accent),
 ('cursor', accent), ('cursor_text_color', bg),
 ('url_color', bb('base0c', '#a2e2e8')),
 ('active_border_color', accent), ('inactive_border_color', bb('base02', '#24304a')),
 ('active_tab_background', accent), ('active_tab_foreground', bg),
 ('inactive_tab_foreground', bb('base04', '#a6b6cf')), ('inactive_tab_background', bb('base01', '#161d2b')),
 ('color0', bb('base00', '#1a2233')), ('color8', bb('base03', '#45526e')),
 ('color1', bb('base08', '#f38ba8')), ('color9', bb('base08', '#f5a0b8')),
 ('color2', bb('base0b', '#a6e3a1')), ('color10', bb('base0b', '#b9ebb4')),
 ('color3', bb('base0a', '#f4c542')), ('color11', bb('base0a', '#f7d574')),
 ('color4', bb('base0d', '#63c7dd')), ('color12', bb('base0d', '#8ad7e8')),
 ('color5', bb('base0e', '#cba6f7')), ('color13', bb('base0e', '#d9c1fa')),
 ('color6', bb('base0c', '#a2e2e8')), ('color14', bb('base0c', '#bfeef2')),
 ('color7', bb('base05', '#dfe7f2')), ('color15', bb('base06', '#ffffff')),
]
with open(kitty, 'w') as f:
    f.write('# generated by sea-shell matugen — regenerated on every wallpaper change\n')
    for k, v in m: f.write('%-22s %s\n' % (k, v))

# LIGHT variant — matugen's base16 "light" colours are pale, low-contrast pastels that wash
# out on a light background (a cyan wallpaper gives a garish cyan bg + unreadable grey text).
# So build a READABLE light theme instead: a near-white background gently tinted from the
# wallpaper accent, near-black text, dark saturated ANSI colours (Latte-style), and the
# accent itself (darkened to read on white) for cursor / selection / borders / tabs / blue.
# sea-apply-mode.sh copies this into kitty-mode.conf in light mode when matugen is on.
def darken(hx, amt=0.35):
    h = hx.lstrip('#'); r, g, b2 = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
    return '#%02x%02x%02x' % (int(r*(1-amt)), int(g*(1-amt)), int(b2*(1-amt)))
lbg  = lighten(accent, 0.90)   # near-white with just a whisper of the accent hue
ltab = lighten(accent, 0.80)
lacc = darken(accent, 0.42)    # accent darkened enough to read as a colour on white
ml = [
 ('foreground', '#14212e'), ('background', lbg),
 ('selection_foreground', lbg), ('selection_background', lacc),
 ('cursor', lacc), ('cursor_text_color', lbg),
 ('url_color', '#1e6688'),
 ('active_border_color', lacc), ('inactive_border_color', '#b6c9d7'),
 ('active_tab_background', lacc), ('active_tab_foreground', lbg),
 ('inactive_tab_foreground', '#465c6f'), ('inactive_tab_background', ltab),
 ('background_opacity', '0.94'),
 ('color0', '#4c586b'), ('color8', '#6a7688'),
 ('color1', '#c81e3f'), ('color9', '#d20f39'),
 ('color2', '#2f8f4e'), ('color10', '#40883f'),
 ('color3', '#9a6b00'), ('color11', '#b9820f'),
 ('color4', lacc),      ('color12', darken(accent, 0.22)),
 ('color5', '#7a35d0'), ('color13', '#8839ef'),
 ('color6', '#157e86'), ('color14', '#1e88a8'),
 ('color7', '#3c4658'), ('color15', '#0c1520'),
]
kl = (kitty[:-5] if kitty.endswith('.conf') else kitty) + '-light.conf'
with open(kl, 'w') as f:
    f.write('# generated by sea-shell matugen (readable light variant)\n')
    for k, v in ml: f.write('%-22s %s\n' % (k, v))
print(accent, lighten(accent))
PY
)
rm -f "$jf"

# starship — swap the sea accents (#63c7dd / #a2e2e8) for the wallpaper palette.
# Seed a pristine default once (deref the symlink), then always generate from it.
set -- $pal; accent="$1"; frost="$2"
[ -f "$sdef" ] || { [ -e "$star" ] && cp -L "$star" "$sdef" 2>/dev/null; }
if [ -f "$sdef" ] && [ -n "$accent" ] && [ -n "$frost" ]; then
    sed -e "s/#63c7dd/$accent/g" -e "s/#a2e2e8/$frost/g" "$sdef" > "$star.tmp" 2>/dev/null && mv "$star.tmp" "$star"
fi

reload_kitty
notify-send 'sea-shell' 'Colours matched to wallpaper 🎨' 2>/dev/null
