#!/bin/sh
# sea-shell — push the shell's light/dark choice out to the SYSTEM so everything else
# follows, not just the bar:
#   • gsettings color-scheme  → GTK apps + browsers (prefers-color-scheme, read through
#                               xdg-desktop-portal) flip with the shell. adw-gtk3 already
#                               tracks color-scheme, so we don't touch the theme name.
#   • kitty                   → write a light palette override (dark fonts on a light bg)
#                               or clear it for dark, then live-reload via SIGUSR1.
#
# Called by shell.qml whenever `mode` changes in appearance.json (which is where the
# SUPER+⇧+D key, the settings toggle, and the auto-dark schedule all write). Usage:
#   sea-apply-mode.sh light | dark
mode="$1"
[ "$mode" = "light" ] || mode="dark"

d="$HOME/.config/sea-shell"
kmode="$d/kitty-mode.conf"
mkdir -p "$d"

if [ "$mode" = "light" ]; then
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' 2>/dev/null || true

    # Latte-derived sea palette — deliberately DARK, saturated fonts so text stays crisp
    # on the light background (the low-contrast pastels of dark mode wash out on white).
    # This include sits after the dark base + matugen in sea-cyan.conf, so it wins.
    cat > "$kmode" <<'EOF'
# sea-shell light mode — generated by sea-apply-mode.sh (overrides the dark base)
foreground              #0c1520
background              #eaf1f6
selection_foreground    #eaf1f6
selection_background    #2f7fa8
cursor                  #1e6688
cursor_text_color       #eaf1f6
url_color               #1e6688
active_border_color     #2f7fa8
inactive_border_color   #b6c9d7
bell_border_color       #b9820f
active_tab_foreground   #eaf1f6
active_tab_background    #2f7fa8
inactive_tab_foreground #465c6f
inactive_tab_background  #dbe6ee
background_opacity      0.94
# normal / bright — darker & more saturated for readability on a light background
color0  #4c586b
color8  #6a7688
color1  #c81e3f
color9  #d20f39
color2  #2f8f4e
color10 #40883f
color3  #9a6b00
color11 #b9820f
color4  #1e66a8
color12 #2f7fa8
color5  #7a35d0
color13 #8839ef
color6  #157e86
color14 #1e88a8
color7  #3c4658
color15 #0c1520
EOF
else
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null || true
    : > "$kmode"        # empty → the dark base (sea-cyan.conf + matugen) applies
fi

pkill -USR1 -x kitty 2>/dev/null || true
