#!/bin/sh
# sea-shell — push the shell's light/dark choice out to the SYSTEM so everything else
# follows, not just the bar:
#   • gsettings color-scheme  → GTK apps + browsers (prefers-color-scheme, read through
#                               xdg-desktop-portal) flip with the shell. adw-gtk3 already
#                               tracks color-scheme, so we don't touch the theme name.
#   • kitty                   → write a light palette override (dark fonts on a light bg)
#                               or clear it for dark, then live-reload via SIGUSR1.
#
# Called by shell.qml whenever `mode` changes in appearance.json (which is where the
# SUPER+⇧+D key, the settings toggle, and the auto-dark schedule all write). Usage:
#   sea-apply-mode.sh light | dark
mode="$1"
[ "$mode" = "light" ] || mode="dark"

d="$HOME/.config/sea-shell"
kmode="$d/kitty-mode.conf"
mkdir -p "$d"

# THE ACCENT HAS A LIGHT CUT AND A DARK CUT and they are not interchangeable.
# Material publishes `primary` twice: a pale one to sit on a dark surface and a
# darker one to sit on a pale surface. Switching the shell between them without
# re-deriving the accent leaves the wrong cut in place -- a pale accent on a white
# background measured 1.5:1, where 3:1 is the floor for something you are meant to
# be able to see. So a mode change re-runs the derivation, but only when matching
# is on; a hand-picked accent is the user's and stays exactly as picked.
rederive_accent() {
    m=$(python3 -c "import json,sys; print(str(json.load(open(sys.argv[1])).get('matugen', False)))" "$d/appearance.json" 2>/dev/null)
    [ "$m" = "True" ] || return 0
    for c in "$(dirname "$0")/matugen-accent.sh" "$HOME/.config/quickshell/sea-shell/matugen-accent.sh"; do
        [ -f "$c" ] && { sh "$c" >/dev/null 2>&1 & return 0; }
    done
}

if [ "$mode" = "light" ]; then
    # Check if user has a forced app preference (dark/light independent from the shell)
    appMode=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1])).get('appMode','auto'))" "$d/appearance.json" 2>/dev/null)
    case "$appMode" in
        dark)  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'  2>/dev/null || true ;;
        light) gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' 2>/dev/null || true ;;
        *)     gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' 2>/dev/null || true ;;
    esac

    # If "match colours" (matugen) is on and a wallpaper-matched light palette exists, use it
    # so light mode is themed to the wallpaper just like dark mode. Otherwise fall back to the
    # fixed sea-light palette below. Either way it lands in kitty-mode.conf (wins in sea-cyan).
    lm="$d/kitty-matugen-light.conf"
    matugen_on=$(python3 -c "import json,sys; print(str(json.load(open(sys.argv[1])).get('matugen', False)))" "$HOME/.config/sea-shell/appearance.json" 2>/dev/null)
    if [ "$matugen_on" = "True" ] && [ -s "$lm" ]; then
        cp "$lm" "$kmode"
        pkill -USR1 -x kitty 2>/dev/null || true
        rederive_accent
        exit 0
    fi

    # Latte-derived sea palette — deliberately DARK, saturated fonts so text stays crisp
    # on the light background (the low-contrast pastels of dark mode wash out on white).
    # This include sits after the dark base + matugen in sea-cyan.conf, so it wins.
    cat > "$kmode" <<'EOF'
# sea-shell light mode — generated by sea-apply-mode.sh (overrides the dark base)
foreground              #0c1520
background              #eaf1f6
selection_foreground    #eaf1f6
selection_background    #2f7fa8
cursor                  #1e6688
cursor_text_color       #eaf1f6
url_color               #1e6688
active_border_color     #2f7fa8
inactive_border_color   #b6c9d7
bell_border_color       #b9820f
active_tab_foreground   #eaf1f6
active_tab_background    #2f7fa8
inactive_tab_foreground #465c6f
inactive_tab_background  #dbe6ee
background_opacity      0.94
# normal / bright — darker & more saturated for readability on a light background
color0  #4c586b
color8  #6a7688
color1  #c81e3f
color9  #d20f39
color2  #2f8f4e
color10 #40883f
color3  #9a6b00
color11 #b9820f
color4  #1e66a8
color12 #2f7fa8
color5  #7a35d0
color13 #8839ef
color6  #157e86
color14 #1e88a8
color7  #3c4658
color15 #0c1520
EOF
else
    appMode=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1])).get('appMode','auto'))" "$d/appearance.json" 2>/dev/null)
    case "$appMode" in
        dark)  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'  2>/dev/null || true ;;
        light) gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' 2>/dev/null || true ;;
        *)     gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'  2>/dev/null || true ;;
    esac
    : > "$kmode"        # empty → the dark base (sea-cyan.conf + matugen) applies
fi

pkill -USR1 -x kitty 2>/dev/null || true
rederive_accent
